services:
  backend:
    build:
      context: ./backend
    container_name: python-backend
    environment:
     - SNOWFLAKE_CONNECTION="MY CONNECTION"
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
